#
# Copyright (C) 2024 nosignals
#
name: Building Neko

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Neko version'
        required: true
        default: '1.2.0-beta'
        type: string
      letak:
        description: 'letak file'
        required: true
        default: ''
        type: string 
      nama:
        description: 'nama app'
        required: true
        default: ''
        type: string  
      changelog:
        description: 'Changelog'
        required: true
        default: '-'
        type: string
      url:
        description: 'url'
        required: false
        default: 'git clone'
        type: string  
        
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build Neko
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 23.05.4
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          
      - name: Preparing Neko
        run: |
              echo ""
              ${{ inputs.url }}
              mkdir feeds artifacts
              cp -rf ./${{ inputs.letak }} ./feeds
        
      - name: Building luci-app-neko
        uses: nosignals/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: ${{ inputs.nama }}
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v4
        with:
          name: neko-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/${{ inputs.nama }}*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v4
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./neko-23.05.4_x86_64/${{ inputs.nama }}* ./release/${{ inputs.nama }}_${{ inputs.version }}_all.ipk
        
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          tag: luci-app-neko_${{ inputs.version }}
          file_glob: true
          body: |
            # LUCI APP NEKO ${{ inputs.version }}
            Simple Clash TUN based Proxy
            ### Information
            - Changelog : 
              - ${{ inputs.changelog }}
            - Default Config : 
              - config.yaml : minimal Configs for Neko (only 1 rules) - Secret : ` sign `
              - nosignals.yaml : 2 rules can added (Block Host, Game) - Secret : ` telekulo `
            ### Dependency Requirement
            - ` bash, kmod-tun, php, php-cgi ` (install PHP Manually before install Neko)
            - Openwrt 23: ` php8 php8-cgi nftables mihomo` 
